name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: Set NODE_VERSION
        run: echo "NODE_VERSION=$(cat .node-version)" >> "$GITHUB_ENV"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test -- --ci --coverage --reporters=default --reporters=jest-junit

      - name: Get base image digest
        id: get-digest
        run: |
          podman pull node:${{ env.NODE_VERSION }}-alpine
          DIGEST=$(podman images --filter=reference="node:${{ env.NODE_VERSION }}-alpine" --digests --format json | jq -r '.[0].Digest')
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Get tag version
        id: get-tag
        run: |
          TAG=$(echo ${{ github.ref_name }} | cut -c 2-)
          echo "tag-version=$TAG" >> "$GITHUB_OUTPUT"

      - name: Get build timestamp
        id: get-timestamp
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "timestamp=$TIMESTAMP" >> "$GITHUB_OUTPUT"

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: opencastsoftware/govuk-nunjucks-renderer
          tags: latest ${{ github.sha }} ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') && steps.get-tag.outputs.tag_version || '' }}
          labels: |
            org.opencontainers.image.created=${{ steps.get-timestamp.outputs.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.base.name=docker.io/library/node:${{ env.NODE_VERSION }}-alpine
            org.opencontainers.image.base.digest=${{ steps.get-digest.outputs.digest }}
            ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') && format('org.opencontainers.image.version={0}', steps.get-tag.outputs.tag_version) || '' }}
          containerfiles: ./Containerfile
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}

      - name: Push image to GitHub Packages
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/opencastsoftware
          username: ${{ github.actor }}
          password: ${{ github.token }}
          image: ${{ steps.build_image.outputs.image-with-tag }}
          tags: ${{ steps.build_image.outputs.tags }}

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: junit.xml
